name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_REPO: 607700977843.dkr.ecr.us-east-2.amazonaws.com/strapi-varun-ecr-repo
      AWS_REGION: us-east-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set dynamic image tag using GitHub run number
        id: set_tag
        run: |
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV

      - name: Build and push Docker image
        working-directory: ./Strapi-app
        run: |
          docker build -t $IMAGE_REPO:$IMAGE_TAG .
          docker push $IMAGE_REPO:$IMAGE_TAG

      - name: Commit image tag to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          echo "$IMAGE_TAG" > image_tag.txt
          git add image_tag.txt
          git diff --cached --quiet || git commit -m "Update image tag to $IMAGE_TAG"
          git push origin main || true